from django.urls import path
from allauth.account import views as account_views

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("account/", views.account_home, name="account_home"),
    path("profile/", views.profile_home, name="profile_home"),
    path("notifications/", views.notification_center, name="notification_center"),
    path("notifications/read-all/", views.notification_mark_all_read, name="notification_mark_all_read"),
    path("notifications/<int:notification_id>/open/", views.notification_open, name="notification_open"),
    path("about/", views.about, name="about"),
    path("shop/", views.shop, name="shop"),
    path("contact/", views.contact, name="contact"),
    path("partners/register/", views.partner_registration, name="partner_registration"),
    path("customers/register/", views.customer_registration, name="customer_registration"),
    path("partners/login/", account_views.LoginView.as_view(template_name="account/login.html"), name="partner_login"),
    path("partners/logout/", account_views.LogoutView.as_view(), name="partner_logout"),
    path("partner/", views.partner_dashboard, name="partner_dashboard"),
    path("partner/profile/", views.partner_profile, name="partner_profile"),
    path("partner/documents/", views.partner_documents, name="partner_documents"),
    path("partner/gallery/", views.partner_gallery, name="partner_gallery"),
    path("partner/gallery/<int:photo_id>/delete/", views.partner_gallery_delete, name="partner_gallery_delete"),
    path("partner/availability/", views.partner_availability, name="partner_availability"),
    path("partner/availability/<int:entry_id>/delete/", views.partner_availability_delete, name="partner_availability_delete"),
    path("partner/offers/<int:offer_id>/<str:decision>/", views.partner_offer_response, name="partner_offer_response"),
    path("partner/documents/<int:document_id>/download/", views.partner_document_download, name="partner_document_download"),
    path("partner/tasks/<int:task_id>/", views.partner_task_detail, name="partner_task_detail"),
    path("partner/tasks/<int:task_id>/update/", views.partner_task_update, name="partner_task_update"),
    path("customer/", views.customer_dashboard, name="customer_dashboard"),
    path("customer/profile/", views.customer_profile, name="customer_profile"),
    path("customer/addresses/<int:address_id>/delete/", views.customer_address_delete, name="customer_address_delete"),
    path("customer/requests/<uuid:public_id>/", views.customer_quote_detail, name="customer_quote_detail"),
    path("customer/payments/<int:payment_id>/receipt/", views.customer_payment_receipt, name="customer_payment_receipt"),
    path("customer/ceremonies/<uuid:public_id>/cancel/", views.customer_request_cancellation, name="customer_request_cancellation"),
    path("customer/ceremonies/<uuid:public_id>/review/", views.customer_submit_review, name="customer_submit_review"),
    path("quote/<uuid:public_id>/contact/", views.quote_contact, name="quote_contact"),
    path("quote/<uuid:public_id>/success/", views.quote_success, name="quote_success"),
    path("quote/<uuid:public_id>/review/", views.quote_review, name="quote_review"),
    path("quote/<uuid:public_id>/<str:decision>/", views.quote_decision, name="quote_decision"),
    path("ceremony/<uuid:public_id>/payment/", views.ceremony_payment, name="ceremony_payment"),
    path(
        "ceremony/<uuid:public_id>/payment/<str:choice>/checkout/",
        views.start_payment_checkout,
        name="start_payment_checkout",
    ),
    path("payments/stripe/webhook/", views.stripe_webhook, name="stripe_webhook"),
    path("dashboard/", views.operations_dashboard, name="operations_dashboard"),
    path("dashboard/insights/", views.business_insights, name="business_insights"),
    path("dashboard/content/", views.content_library, name="content_library"),
    path("dashboard/content/community/<str:content_type>/<int:item_id>/<str:decision>/", views.moderate_community_content, name="moderate_community_content"),
    path("dashboard/content/published/<str:content_type>/<int:item_id>/<str:field>/", views.toggle_published_content, name="toggle_published_content"),
    path("dashboard/quotes/", views.quote_requests, name="quote_requests"),
    path("dashboard/quote/<uuid:public_id>/", views.manage_quote, name="manage_quote"),
    path("dashboard/quote/<uuid:public_id>/availability-offer/", views.create_availability_offer, name="create_availability_offer"),
    path("dashboard/ceremonies/", views.ceremonies, name="ceremonies"),
    path("dashboard/ceremonies/<uuid:public_id>/", views.ceremony_detail, name="ceremony_detail"),
    path("dashboard/ceremonies/<uuid:public_id>/assign/", views.assign_partner, name="assign_partner"),
    path("dashboard/ceremonies/<uuid:public_id>/complete/", views.complete_job, name="complete_job"),
    path("dashboard/customer-cancellations/<int:request_id>/<str:decision>/", views.review_customer_cancellation, name="review_customer_cancellation"),
    path("dashboard/ceremonies/<uuid:public_id>/partner-payout/", views.manage_partner_payout, name="manage_partner_payout"),
    path(
        "dashboard/ceremonies/<uuid:public_id>/payment/full/",
        views.record_full_payment,
        name="record_full_payment",
    ),
    path(
        "dashboard/ceremonies/<uuid:public_id>/payment/<str:payment_type>/",
        views.record_payment,
        name="record_payment",
    ),
    path(
        "dashboard/ceremonies/<uuid:public_id>/payment/<str:payment_type>/status/<str:new_status>/",
        views.update_payment_status,
        name="update_payment_status",
    ),
    path(
        "dashboard/ceremonies/<uuid:public_id>/outcome/<str:outcome>/",
        views.record_outcome,
        name="record_outcome",
    ),
    path("dashboard/partners/", views.partners, name="partners"),
    path("dashboard/partners/new/", views.manage_partner, name="add_partner"),
    path("dashboard/partners/<int:partner_id>/", views.manage_partner, name="manage_partner"),
    path("dashboard/partner-documents/<int:document_id>/<str:decision>/", views.review_partner_document, name="review_partner_document"),
]
