# Generated by Django 5.2.16 on 2026-07-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('partner_type', models.CharField(choices=[('restaurant', 'Restaurant partner'), ('individual', 'Individual ambassador')], default='restaurant', max_length=20)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('service_area', models.CharField(help_text='Cities, ZIPs, or radius served', max_length=180)),
                ('food_permit_verified', models.BooleanField(default=False)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('cultural_training_verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('event_type', models.CharField(choices=[('home', 'Home gathering'), ('wedding', 'Wedding'), ('graduation', 'Graduation'), ('corporate', 'Corporate event'), ('cultural', 'Cultural program'), ('other', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location', models.CharField(help_text='Address, city, or ZIP', max_length=220)),
                ('guest_count', models.PositiveIntegerField()),
                ('indoor', models.BooleanField(default=True)),
                ('milk_preference', models.CharField(choices=[('yes', 'Yes, include milk'), ('no', 'No milk'), ('non_dairy', 'Non-dairy option'), ('unsure', 'Not sure yet')], default='unsure', max_length=20)),
                ('snack_style', models.CharField(choices=[('shared', 'Traditional shared plate with utensil'), ('individual', 'Individual portions'), ('recommend', 'Ambassador recommendation')], default='recommend', max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='bookings.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
