# Generated by Django 5.2.16 on 2026-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_quoterequest_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='customer_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quote_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quote_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quote_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
