# Generated by Django 5.2.16 on 2026-07-14 23:40

import django.db.models.deletion
import uuid
from datetime import datetime, time, timedelta
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_existing_workflows(apps, schema_editor):
    QuoteRequest = apps.get_model('bookings', 'QuoteRequest')
    Ceremony = apps.get_model('bookings', 'Ceremony')
    Payment = apps.get_model('bookings', 'Payment')
    StatusHistory = apps.get_model('bookings', 'StatusHistory')

    operational_statuses = {'accepted', 'assigned', 'completed', 'cancelled'}
    for quote in QuoteRequest.objects.filter(status__in=operational_statuses):
        total = quote.quoted_amount or Decimal('0.00')
        deposit = quote.deposit_amount or Decimal('0.00')
        event_time = quote.event_time or time(0, 0)
        event_at = timezone.make_aware(
            datetime.combine(quote.event_date, event_time),
            timezone.get_current_timezone(),
        )
        final_due = event_at - timedelta(hours=24)

        if quote.status == 'assigned':
            ceremony_status = 'assigned'
        elif quote.status == 'completed':
            ceremony_status = 'completed'
        elif quote.status == 'cancelled':
            ceremony_status = 'cancelled'
        else:
            ceremony_status = 'awaiting_deposit' if deposit > 0 else 'awaiting_partner'

        ceremony = Ceremony.objects.create(
            quote_id=quote.pk,
            assigned_partner_id=quote.assigned_partner_id,
            status=ceremony_status,
            final_payment_due_at=final_due,
            completed_at=timezone.now() if ceremony_status == 'completed' else None,
            cancelled_at=timezone.now() if ceremony_status == 'cancelled' else None,
        )

        deposit_paid = quote.status in {'assigned', 'completed'}
        final_paid = quote.status == 'completed'
        Payment.objects.create(
            ceremony_id=ceremony.pk,
            payment_type='deposit',
            status='paid' if deposit_paid and deposit > 0 else ('waived' if deposit == 0 else 'pending'),
            expected_amount=deposit,
            received_amount=deposit if deposit_paid else Decimal('0.00'),
            due_at=quote.quote_expires_at or timezone.now() + timedelta(days=2),
            paid_at=timezone.now() if deposit_paid and deposit > 0 else None,
            notes='Migrated from the legacy workflow; paid state was inferred.' if deposit_paid else '',
        )
        final_amount = max(total - deposit, Decimal('0.00'))
        Payment.objects.create(
            ceremony_id=ceremony.pk,
            payment_type='final',
            status='paid' if final_paid and final_amount > 0 else ('waived' if final_amount == 0 else 'pending'),
            expected_amount=final_amount,
            received_amount=final_amount if final_paid else Decimal('0.00'),
            due_at=final_due,
            paid_at=timezone.now() if final_paid and final_amount > 0 else None,
            notes='Migrated from the legacy workflow; paid state was inferred.' if final_paid else '',
        )
        StatusHistory.objects.create(
            ceremony_id=ceremony.pk,
            from_status='',
            to_status=ceremony_status,
            note=f'Migrated from legacy quote status: {quote.status}.',
        )
        quote.status = 'accepted'
        quote.save(update_fields=['status'])


def reverse_existing_workflows(apps, schema_editor):
    Payment = apps.get_model('bookings', 'Payment')
    StatusHistory = apps.get_model('bookings', 'StatusHistory')
    Ceremony = apps.get_model('bookings', 'Ceremony')
    Payment.objects.all().delete()
    StatusHistory.objects.all().delete()
    Ceremony.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_quoterequest_customer_decision_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('awaiting_deposit', 'Awaiting deposit'), ('awaiting_partner', 'Awaiting partner'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('at_risk', 'Payment overdue'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='awaiting_deposit', max_length=24)),
                ('final_payment_due_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_reason', models.CharField(blank=True, choices=[('customer_cancelled', 'Customer cancelled'), ('bunago_cancelled', 'BunaGo cancelled'), ('partner_unavailable', 'Partner unavailable'), ('customer_no_show', 'Customer no-show'), ('partner_no_show', 'Partner no-show'), ('venue_access', 'Venue or access problem'), ('weather_emergency', 'Weather or emergency'), ('deposit_not_paid', 'Deposit not paid'), ('final_payment_not_paid', 'Final payment not paid'), ('other', 'Other')], max_length=32)),
                ('outcome_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceremonies', to='bookings.partner')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ceremony', to='bookings.quoterequest')),
            ],
            options={
                'ordering': ['quote__event_date', 'quote__event_time'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='bookings.ceremony')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('deposit', 'Initial deposit'), ('final', 'Final payment'), ('refund', 'Refund')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited'), ('waived', 'Waived')], default='pending', max_length=16)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.ceremony')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('ceremony', 'payment_type'), name='unique_payment_type_per_ceremony')],
            },
        ),
        migrations.RunPython(migrate_existing_workflows, reverse_existing_workflows),
        migrations.RemoveField(
            model_name='quoterequest',
            name='assigned_partner',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='new', max_length=20),
        ),
    ]
