# Generated by Django 5.2.16 on 2026-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_quoterequest_assigned_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('awaiting_deposit', 'Awaiting deposit'), ('awaiting_partner', 'Awaiting partner'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('at_risk', 'Payment overdue'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], max_length=24),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='to_status',
            field=models.CharField(choices=[('awaiting_deposit', 'Awaiting deposit'), ('awaiting_partner', 'Awaiting partner'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('at_risk', 'Payment overdue'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], max_length=24),
        ),
    ]
