# Generated by Django 5.2.16 on 2026-07-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_statushistory_from_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('provider_session_id', models.CharField(max_length=160, unique=True)),
                ('provider_payment_reference', models.CharField(blank=True, max_length=160)),
                ('payment_choice', models.CharField(choices=[('deposit', 'Deposit only'), ('final', 'Final balance'), ('full', 'Pay in full')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='created', max_length=16)),
                ('checkout_url', models.URLField(max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='bookings.ceremony')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
