# Generated by Django 5.2.16 on 2026-07-15 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_ceremony_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('needs_info', 'More information needed'), ('approved', 'Approved'), ('rejected', 'Not approved')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='payout_destination',
            field=models.CharField(blank=True, help_text='Payout email or masked account label. Do not enter a full bank/card number.', max_length=160),
        ),
        migrations.AddField(
            model_name='partner',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('ach', 'Bank transfer / ACH'), ('check', 'Check'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('food_permit', 'Food-service permit'), ('insurance', 'Insurance certificate'), ('identity', 'Identity document'), ('training', 'Training certificate'), ('tax', 'Tax form'), ('other', 'Other supporting document')], max_length=24)),
                ('file', models.FileField(upload_to='partner_documents/%Y/%m/')),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.partner')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('delivered', 'Marked delivered'), ('issue', 'Issue reported'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('partner_notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ceremony', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_task', to='bookings.ceremony')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='bookings.partner')),
            ],
            options={
                'ordering': ['ceremony__quote__event_date'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('not_ready', 'Not ready'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('held', 'On hold'), ('cancelled', 'Cancelled')], default='not_ready', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='bookings.partner')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='bookings.partnertask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
