# Generated by Django 5.2.16 on 2026-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_partner_address_partner_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdocument',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Staff-only validity end date. Leave blank when the document does not expire.', null=True),
        ),
        migrations.AddField(
            model_name='partnerdocument',
            name='expiry_processed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
    ]
