# Generated by Django 5.2.16 on 2026-07-15 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_customerprofile_customercancellationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='coverage_status',
            field=models.CharField(choices=[('unreserved', 'No partner reserved'), ('held', 'Partner held'), ('confirmed', 'Partner confirmed'), ('uncovered', 'Partner coverage needed')], default='unreserved', max_length=16),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='cleanup_buffer_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='setup_buffer_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('waitlisted', 'Waiting for partner'), ('quoted', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='AvailabilityOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('response_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_offers', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_offers', to='bookings.partner')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_offers', to='bookings.quoterequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacityHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('temporary', 'Temporary hold'), ('confirmed', 'Customer confirmed'), ('converted', 'Converted to assignment'), ('released', 'Released'), ('expired', 'Expired')], default='temporary', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_hold', to='bookings.availabilityoffer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_holds', to='bookings.partner')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_holds', to='bookings.quoterequest')),
            ],
            options={
                'ordering': ['event_start'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='bookings.partner')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
