# Generated by Django 5.2.16 on 2026-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_ceremony_coverage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='outcome_reason',
            field=models.CharField(blank=True, choices=[('customer_cancelled', 'Customer cancelled'), ('bunago_cancelled', 'Akako House cancelled'), ('partner_unavailable', 'Partner unavailable'), ('customer_no_show', 'Customer no-show'), ('partner_no_show', 'Partner no-show'), ('venue_access', 'Venue or access problem'), ('weather_emergency', 'Weather or emergency'), ('deposit_not_paid', 'Deposit not paid'), ('final_payment_not_paid', 'Final payment not paid'), ('other', 'Other')], max_length=32),
        ),
    ]
