# Generated by Django 5.2.16 on 2026-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_clientorganization_eventphoto_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='placement',
            field=models.CharField(choices=[('gallery', 'Homepage event gallery'), ('about_origin', 'About page — land of origins'), ('about_ceremony', 'About page — ceremony and hospitality')], default='gallery', help_text='Choose where this approved photograph should appear.', max_length=24),
        ),
    ]
