# Generated by Django 5.2.16 on 2026-07-16 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_eventphoto_placement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('quote_new', 'New quote request'), ('quote_accepted', 'Quote accepted'), ('quote_expired', 'Quote expired'), ('payment_received', 'Payment received'), ('payment_due', 'Payment approaching'), ('payment_overdue', 'Payment overdue'), ('partner_assigned', 'Partner assignment'), ('partner_accepted', 'Partner acceptance'), ('ceremony_reminder', 'Ceremony reminder'), ('document_expiring', 'Document expiring'), ('document_expired', 'Document expired'), ('gallery_uploaded', 'Gallery upload'), ('review_submitted', 'Review submitted')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('email_status', models.CharField(choices=[('skipped', 'Not requested'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='skipped', max_length=16)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.CharField(blank=True, max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='bookings_no_recipie_8bb0f2_idx'), models.Index(fields=['kind', '-created_at'], name='bookings_no_kind_fc5a2c_idx')],
            },
        ),
    ]
