# Generated by Django 5.2.16 on 2026-07-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('purchase_frequency', models.CharField(blank=True, choices=[('weekly', 'Every week'), ('biweekly', 'Every two weeks'), ('monthly', 'About once a month'), ('occasionally', 'Occasionally'), ('exploring', 'I am just exploring')], max_length=20)),
                ('marketing_consent', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
