# Generated by Django 5.2.16 on 2026-07-17 04:21

import bookings.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_shopinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorganization',
            name='logo',
            field=models.FileField(storage=bookings.storage.public_media_storage, upload_to='content/client_logos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.FileField(storage=bookings.storage.public_media_storage, upload_to='content/event_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='file',
            field=models.FileField(storage=bookings.storage.private_document_storage, upload_to='partner_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='partnergalleryphoto',
            name='image',
            field=models.FileField(storage=bookings.storage.public_media_storage, upload_to='partner_gallery/%Y/%m/'),
        ),
    ]
