# Generated by Django 5.2.16 on 2026-08-13 16:18

import bookings.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_amend_service_terms_smoke_safety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=20)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField(blank=True)),
                ('description', models.CharField(default='Corporate event coffee service', max_length=240)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('first_payment_due_date', models.DateField(blank=True, null=True)),
                ('balance_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, storage=bookings.storage.private_document_storage, upload_to='invoices/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_emailed_to', models.EmailField(blank=True, max_length=254)),
                ('last_emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=240)),
                ('email_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bookings.ceremony')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank transfer / ACH'), ('zelle', 'Zelle'), ('check', 'Check'), ('cash', 'Cash'), ('other', 'Other')], default='other', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bookings.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
    ]
