# Generated by Django 5.2.16 on 2026-08-13 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_replace_legacy_bunago_quote_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('quote_new', 'New quote request'), ('quote_accepted', 'Quote accepted'), ('quote_declined', 'Quote declined'), ('quote_expired', 'Quote expired'), ('payment_received', 'Payment received'), ('booking_confirmed', 'Booking confirmed'), ('booking_paid', 'Booking paid in full'), ('payment_due', 'Payment approaching'), ('payment_overdue', 'Payment overdue'), ('partner_assigned', 'Partner assignment'), ('partner_accepted', 'Partner acceptance'), ('capacity_hold_created', 'Temporary reservation created'), ('capacity_hold_released', 'Temporary reservation released'), ('ceremony_reminder', 'Ceremony reminder'), ('ceremony_completed', 'Ceremony completed'), ('document_expiring', 'Document expiring'), ('document_expired', 'Document expired'), ('gallery_uploaded', 'Gallery upload'), ('review_submitted', 'Review submitted')], max_length=32),
        ),
        migrations.CreateModel(
            name='BookingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('quote_accepted', 'Quote accepted'), ('invoice_sent', 'Invoice sent'), ('deposit_pending', 'Initial payment pending'), ('deposit_received', 'Initial payment received'), ('booking_confirmed', 'Booking confirmed'), ('balance_pending', 'Balance pending'), ('paid_in_full', 'Paid in full'), ('event_ready', 'Event ready'), ('completed', 'Completed')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('reached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='bookings.ceremony')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reached_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('ceremony', 'stage'), name='unique_ceremony_booking_milestone')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='bookings.payment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='bookings.invoicetransaction')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'payment'), name='unique_transaction_payment_allocation')],
            },
        ),
    ]
