# Generated by Django 5.2.16 on 2026-08-13 23:17

import bookings.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_alter_notification_kind_bookingmilestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('pdf_file', models.FileField(storage=bookings.storage.private_document_storage, upload_to='invoice_versions/%Y/%m/')),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='bookings.invoice')),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank transfer / ACH'), ('zelle', 'Zelle'), ('check', 'Check'), ('cash', 'Cash'), ('other', 'Other')], max_length=16)),
                ('payment_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('final_due_date', models.DateField(blank=True, null=True)),
                ('booking_status', models.CharField(max_length=80)),
                ('pdf_file', models.FileField(storage=bookings.storage.private_document_storage, upload_to='payment_receipts/%Y/%m/')),
                ('emailed_to', models.EmailField(blank=True, max_length=254)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='bookings.invoiceversion')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='bookings.invoicetransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoiceversion',
            constraint=models.UniqueConstraint(fields=('invoice', 'revision'), name='unique_invoice_revision'),
        ),
    ]
