# Generated by Django 5.2.16 on 2026-08-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_invoiceversion_paymentreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Company or organization')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='billing_contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='billing_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Company or organization')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='organization_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
