# Generated by Django 5.2.16 on 2026-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_invoice_billing_contact_name_invoice_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='event_access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='event_access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='event_address',
            field=models.TextField(blank=True),
        ),
    ]
